create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  subject text not null,
  message text not null,
  submitted_at timestamptz not null default now()
);

alter table public.contact_submissions
enable row level security;

create or replace function public.submit_contact_submission(
  p_name text,
  p_email text,
  p_phone text,
  p_subject text,
  p_message text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.contact_submissions (name, email, phone, subject, message)
  values (p_name, p_email, p_phone, p_subject, p_message);
end;
$$;

revoke execute on function public.submit_contact_submission(text, text, text, text, text) from public, anon, authenticated;
grant execute on function public.submit_contact_submission(text, text, text, text, text) to service_role;

notify pgrst, 'reload schema';